In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("songs.csv", encoding="latin-1")

print(df.head())

   Unnamed: 0     video_id channelTitle  \
0           0  F44TK5EHCRo     T-Series
1           1  adx8Rsjp-c0     T-Series
2           2  36nQLyrR7Sw     T-Series
3           3  TKbifi5AMQo     T-Series
4           4  NNA21SoGqss     T-Series

                                               title  \
0  RAFTA RAFTA (Lo-Fi Mix) | Dj Moody | KK | Jeet...
1  TUM HO MERA PYAR (Lo-Fi Mix) | Dj Moody | KK, ...
2  ISHQ HOTHON SE (Lo-Fi Mix) (Audio) | Dj Moody ...
3  HUMKO PYAR HUA (Lo-Fi Mix) (Audio) | Dj Moody ...
4  Har Har Mahadev (Lyrical Video): Sachet Tandon...

                                         description  \
0  Presenting the song "RAFTA RAFTA (Lo-Fi Mix)" ...
1  Presenting the song "TUM HO MERA PYAR (Lo-Fi M...
2  Presenting the song "ISHQ HOTHON SE (Lo-Fi Mix...
3  Presenting the song "HUMKO PYAR HUA (Lo-Fi Mix...
4  T-Series Presents "Har Har Mahadev (Lyrical Vi...

                                                tags           publishedAt  \
0  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T12:30:08Z
1  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T10:30:01Z
2  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T09:30:00Z
3  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T07:30:05Z
4  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T05:30:06Z

   viewCount  likeCount  favoriteCount  commentCount duration definition  \
0       7299        241              0            59  PT4M42S         hd
1       4212        144              0            32  PT5M27S         hd
2       2849         79              0            31  PT6M10S         hd
3       3991        116              0            36  PT5M59S         hd
4     101950       6230              0           434  PT3M37S         hd

   caption
0    False
1    False
2    False
3    False
4    False

In [3]:
print("Shape (Rows, Columns):", df.shape)

Shape (Rows, Columns): (19345, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19345 entries, 0 to 19344
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     19345 non-null  int64
 1   video_id       19345 non-null  object
 2   channelTitle   19345 non-null  object
 3   title          19345 non-null  object
 4   description    19342 non-null  object
 5   tags           19345 non-null  object
 6   publishedAt    19345 non-null  object
 7   viewCount      19345 non-null  int64
 8   likeCount      19345 non-null  int64
 9   favoriteCount  19345 non-null  int64
 10  commentCount   19345 non-null  int64
 11  duration       19345 non-null  object
 12  definition     19345 non-null  object
 13  caption        19345 non-null  bool
dtypes: bool(1), int64(5), object(8)
memory usage: 1.9+ MB

In [5]:
print("Missing Values:\n")
print(df.isnull().sum())

Missing Values:

Unnamed: 0       0
video_id         0
channelTitle     0
title            0
description      3
tags             0
publishedAt      0
viewCount        0
likeCount        0
favoriteCount    0
commentCount     0
duration         0
definition       0
caption          0
dtype: int64

In [6]:
print(df.describe(include="all"))

          Unnamed: 0     video_id channelTitle  \
count   19345.000000        19345        19345
unique           NaN        19345            1
top              NaN  F44TK5EHCRo     T-Series
freq             NaN            1        19345
mean     9672.000000          NaN          NaN
std      5584.564814          NaN          NaN
min         0.000000          NaN          NaN
25%      4836.000000          NaN          NaN
50%      9672.000000          NaN          NaN
75%     14508.000000          NaN          NaN
max     19344.000000          NaN          NaN

                                                    title  \
count                                               19345
unique                                              19220
top     Public Review: All Is Well (In Cinemas Now) | ...
freq                                                    4
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                                              description  \
count                                               19342
unique                                              18359
top     Presenting the clips of MTV Hustle 2.0\n\nAfte...
freq                                                   95
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                                                     tags  \
count                                               19345
unique                                              14620
top     ['hindi songs', '2021 hindi songs', 'new hindi...
freq                                                  962
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                 publishedAt     viewCount     likeCount  favoriteCount  \
count                  19345  1.934500e+04  1.934500e+04        19345.0
unique                 19181           NaN           NaN            NaN
top     2023-06-28T13:32:21Z           NaN           NaN            NaN
freq                       7           NaN           NaN            NaN
mean                     NaN  1.193826e+07  8.718149e+04            0.0
std                      NaN  5.484973e+07  3.610099e+05            0.0
min                      NaN  0.000000e+00  0.000000e+00            0.0
25%                      NaN  8.044200e+04  6.440000e+02            0.0
50%                      NaN  3.627810e+05  3.929000e+03            0.0
75%                      NaN  2.613386e+06  2.580300e+04            0.0
max                      NaN  1.536719e+09  1.284022e+07            0.0

         commentCount duration definition caption
count    19345.000000    19345      19345   19345
unique            NaN     1448          2       2
top               NaN    PT30S         hd   False
freq              NaN      392      16583   19144
mean      2636.024141      NaN        NaN     NaN
std      12487.178242      NaN        NaN     NaN
min          0.000000      NaN        NaN     NaN
25%         37.000000      NaN        NaN     NaN
50%        184.000000      NaN        NaN     NaN
75%        961.000000      NaN        NaN     NaN
max     420375.000000      NaN        NaN     NaN

In [7]:
# Remove duplicate videos
df = df.drop_duplicates(subset="video_id")

# Remove rows having missing title
df = df.dropna(subset=["title"])

# Fill missing descriptions
df["description"] = df["description"].fillna("No Description")

# Convert numeric columns
cols = ["viewCount","likeCount","commentCount","favoriteCount"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df.head())

   Unnamed: 0     video_id channelTitle  \
0           0  F44TK5EHCRo     T-Series
1           1  adx8Rsjp-c0     T-Series
2           2  36nQLyrR7Sw     T-Series
3           3  TKbifi5AMQo     T-Series
4           4  NNA21SoGqss     T-Series

                                               title  \
0  RAFTA RAFTA (Lo-Fi Mix) | Dj Moody | KK | Jeet...
1  TUM HO MERA PYAR (Lo-Fi Mix) | Dj Moody | KK, ...
2  ISHQ HOTHON SE (Lo-Fi Mix) (Audio) | Dj Moody ...
3  HUMKO PYAR HUA (Lo-Fi Mix) (Audio) | Dj Moody ...
4  Har Har Mahadev (Lyrical Video): Sachet Tandon...

                                         description  \
0  Presenting the song "RAFTA RAFTA (Lo-Fi Mix)" ...
1  Presenting the song "TUM HO MERA PYAR (Lo-Fi M...
2  Presenting the song "ISHQ HOTHON SE (Lo-Fi Mix...
3  Presenting the song "HUMKO PYAR HUA (Lo-Fi Mix...
4  T-Series Presents "Har Har Mahadev (Lyrical Vi...

                                                tags           publishedAt  \
0  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T12:30:08Z
1  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T10:30:01Z
2  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T09:30:00Z
3  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T07:30:05Z
4  ['hindi songs 2023', 'hindi songs new', 'bolly...  2023-08-20T05:30:06Z

   viewCount  likeCount  favoriteCount  commentCount duration definition  \
0       7299        241              0            59  PT4M42S         hd
1       4212        144              0            32  PT5M27S         hd
2       2849         79              0            31  PT6M10S         hd
3       3991        116              0            36  PT5M59S         hd
4     101950       6230              0           434  PT3M37S         hd

   caption
0    False
1    False
2    False
3    False
4    False

In [8]:
print(df.isnull().sum())

Unnamed: 0       0
video_id         0
channelTitle     0
title            0
description      0
tags             0
publishedAt      0
viewCount        0
likeCount        0
favoriteCount    0
commentCount     0
duration         0
definition       0
caption          0
dtype: int64

In [9]:
df["publishedAt"] = pd.to_datetime(df["publishedAt"])

print(df["publishedAt"].head())

0   2023-08-20 12:30:08+00:00
1   2023-08-20 10:30:01+00:00
2   2023-08-20 09:30:00+00:00
3   2023-08-20 07:30:05+00:00
4   2023-08-20 05:30:06+00:00
Name: publishedAt, dtype: datetime64[ns, UTC]

In [10]:
df["Year"] = df["publishedAt"].dt.year
df["Month"] = df["publishedAt"].dt.month
df["Day"] = df["publishedAt"].dt.day
df["DayOfWeek"] = df["publishedAt"].dt.day_name()
df["Hour"] = df["publishedAt"].dt.hour

df[["publishedAt","Year","Month","DayOfWeek","Hour"]].head()

                publishedAt  Year  Month DayOfWeek  Hour
0 2023-08-20 12:30:08+00:00  2023      8    Sunday    12
1 2023-08-20 10:30:01+00:00  2023      8    Sunday    10
2 2023-08-20 09:30:00+00:00  2023      8    Sunday     9
3 2023-08-20 07:30:05+00:00  2023      8    Sunday     7
4 2023-08-20 05:30:06+00:00  2023      8    Sunday     5

In [11]:
total_videos = len(df)
total_views = df["viewCount"].sum()
total_likes = df["likeCount"].sum()
total_comments = df["commentCount"].sum()
avg_views = df["viewCount"].mean()

print("Total Videos :", total_videos)
print("Total Views :", total_views)
print("Total Likes :", total_likes)
print("Total Comments :", total_comments)
print("Average Views :", avg_views)

Total Videos : 19345
Total Views : 230945654852
Total Likes : 1686525855
Total Comments : 50993887
Average Views : 11938260.783251487

In [12]:
top_views = df.sort_values("viewCount", ascending=False)

top_views[["title","channelTitle","viewCount"]].head(10)

,title,channelTitle,viewCount
6649,"Vaaste Song: Dhvani Bhanushali, Tanishk Bagchi...",T-Series,1536719459
4340,"Lut Gaye (Full Song) Emraan Hashmi, Yukti | Ju...",T-Series,1333673024
7614,DILBAR Lyrical | Satyameva Jayate |John Abraha...,T-Series,1257657363
7023,"SIMMBA: Aankh Marey Lyrical | Ranveer Singh, S...",T-Series,1217598096
9026,Guru Randhawa: High Rated Gabru Official Song ...,T-Series,1183904054
10818,"Cham Cham Full Video | BAAGHI | Tiger Shroff, ...",T-Series,1166497013
8273,Guru Randhawa: Lahore (Official Video) Bhushan...,T-Series,1064521703
8102,Bom Diggy Diggy (VIDEO) | Zack Knight | Jasmi...,T-Series,996655164
7064,Leja Re | Dhvani Bhanushali | Tanishk Bagchi |...,T-Series,957015582
5999,Full Song: KHAIRIYAT (BONUS TRACK) | CHHICHHOR...,T-Series,941903968

In [13]:
top_likes = df.sort_values("likeCount", ascending=False)

top_likes[["title","channelTitle","likeCount"]].head(10)

,title,channelTitle,likeCount
6649,"Vaaste Song: Dhvani Bhanushali, Tanishk Bagchi...",T-Series,12840215
4340,"Lut Gaye (Full Song) Emraan Hashmi, Yukti | Ju...",T-Series,10724344
5999,Full Song: KHAIRIYAT (BONUS TRACK) | CHHICHHOR...,T-Series,7054035
7677,Official Video: Humnava Mere Song | Jubin Naut...,T-Series,6419042
4396,"Saiyaan Ji ? Yo Yo Honey Singh, Neha Kakkar|Nu...",T-Series,6387196
9026,Guru Randhawa: High Rated Gabru Official Song ...,T-Series,6234319
4650,Naach Meri Rani: Guru Randhawa Feat. Nora Fate...,T-Series,6148130
3540,Dil Galti Kar Baitha Hai | Meet Bros Ft. Jubin...,T-Series,6105393
8273,Guru Randhawa: Lahore (Official Video) Bhushan...,T-Series,6024651
6120,"Arijit Singh: Pachtaoge | Vicky Kaushal, Nora ...",T-Series,5990026

In [14]:
channel_views = (
    df.groupby("channelTitle")["viewCount"]
      .sum()
      .sort_values(ascending=False)
)

print(channel_views.head(10))

channelTitle
T-Series    230945654852
Name: viewCount, dtype: int64

In [15]:
channel_videos = (
    df.groupby("channelTitle")["video_id"]
      .count()
      .sort_values(ascending=False)
)

print(channel_videos.head(10))

channelTitle
T-Series    19345
Name: video_id, dtype: int64

In [16]:
yearly_uploads = df.groupby("Year")["video_id"].count()

print(yearly_uploads)

Year
2010       1
2011    4143
2012     789
2013     977
2014     990
2015    1034
2016    1623
2017    1574
2018    1278
2019    1383
2020    1085
2021    1303
2022    1840
2023    1325
Name: video_id, dtype: int64

In [17]:
df["YearMonth"] = df["publishedAt"].dt.to_period("M")

monthly_uploads = df.groupby("YearMonth")["video_id"].count()

print(monthly_uploads)

YearMonth
2010-12      1
2011-01      8
2011-02     25
2011-03     26
2011-04    269
          ...
2023-04    274
2023-05    145
2023-06    149
2023-07    195
2023-08     95
Freq: M, Name: video_id, Length: 152, dtype: int64

C:\Users\Amritanshu\AppData\Local\Temp\ipykernel_23372\842125809.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["YearMonth"] = df["publishedAt"].dt.to_period("M")

In [18]:
top_comments = df.sort_values("commentCount", ascending=False)

top_comments[["title","commentCount"]].head(10)

                                                  title  commentCount
9026  Guru Randhawa: High Rated Gabru Official Song ...        420375
6649  Vaaste Song: Dhvani Bhanushali, Tanishk Bagchi...        353057
6979  Yo Yo Honey Singh: MAKHNA Video Song | Neha Ka...        349430
4340  Lut Gaye (Full Song) Emraan Hashmi, Yukti | Ju...        339000
8273  Guru Randhawa: Lahore (Official Video) Bhushan...        313019
4396  Saiyaan Ji ? Yo Yo Honey Singh, Neha Kakkar|Nu...        283941
4572  First Kiss: Yo Yo Honey Singh Ft. Ipsitaa | Bh...        279736
4812  Dil Ko Maine Di Kasam Video | Amaal M Ft.Ariji...        273862
5999  Full Song: KHAIRIYAT (BONUS TRACK) | CHHICHHOR...        251962
4515  Veham Song: Armaan Malik | Asim Riaz, Sakshi M...        230156

In [19]:
df["EngagementRate"] = (
    (df["likeCount"] + df["commentCount"])
    / df["viewCount"]
) * 100

df["EngagementRate"] = df["EngagementRate"].fillna(0)

top_engagement = df.sort_values(
    "EngagementRate",
    ascending=False
)

top_engagement[
    ["title","EngagementRate"]
].head(10)

                                                  title  EngagementRate
9413  LIVE: Hindi Medium Trailer Launch at Twitter B...             inf
9414  LIVE: Hindi Medium Trailer Launch at Twitter B...             inf
8184                          Millind Gaba Live With Us             inf
9492  LIVE: Siddharth Slathia | TSeries Acoustics So...             inf
9488                                       Naam Shabana             inf
9471               LIVE: Gulaabi 2.0 Song Launch | Noor             inf
9473               LIVE: Gulaabi 2.0 Song Launch | Noor             inf
8183                                       Millind Gaba             inf
9549                  Cheez Badi Launch Event | Machine     2750.000000
8106  Tere Mere Beech Mein Song | Babul Supriyo | La...       49.692043

In [20]:
views = df["viewCount"].dropna().values

print("Mean :", np.mean(views))
print("Median :", np.median(views))
print("Maximum :", np.max(views))
print("Minimum :", np.min(views))
print("Standard Deviation :", np.std(views))

Mean : 11938260.783251487
Median : 362781.0
Maximum : 1536719459
Minimum : 0
Standard Deviation : 54848311.689209096

In [ ]:
df.to_csv("cleaned_songs.csv", index=False)

channel_views.to_csv("channel_views.csv")

top_views.to_csv("top_viewed_songs.csv")

top_likes.to_csv("top_liked_songs.csv")

print("Files Saved Successfully")